name: Deploy Docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: docs/requirements.txt
      - name: Install dependencies
        run: pip install -r docs/requirements.txt
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
